name: oulun_energia_mobile
description: Oulun Energia

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_flavorizr: ^2.1.5
  flutter_svg: ^1.1.6
  http: ^0.13.5
  flutter_secure_storage: ^4.2.1
  flutter_riverpod: ^2.1.1
  xml2json: ^5.3.5
  graphic: ^1.0.1
  step_progress_indicator: ^1.0.2
  swipe: ^0.0.1
  expandable: ^5.0.1
  go_router: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flavorizr:
  flavors:
    production: # flavor to publish from (production signed)
      app:
        name: "Oulun Energia"

      android:
        applicationId: "fi.oulunenergia.pohjoistavoimaa"

      ios:
        bundleId: "fi.oulunenergia.pohjoistavoimaa"

    staging: # flavor for internal/external testing (staging signed)
      app:
        name: "Oulun Energia -staging"

      android:
        applicationId: "fi.oulunenergia.pohjoistavoimaa.dev"
      ios:
        bundleId: "fi.oulunenergia.pohjoistavoimaa.dev"

    dev: # flavor that uses developer's own signature and playground
      app:
        name: "Oulun Energia -dev"

      android:
        applicationId: "fi.oulunenergia.pohjoistavoimaa.dev"
      ios:
        bundleId: "fi.oulunenergia.pohjoistavoimaa.dev"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    # To add assets to your package, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    #
    # For details regarding assets in packages, see
    # https://flutter.dev/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # To add custom fonts to your package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Eina
      fonts:
        - asset: assets/fonts/Eina01-Regular.ttf
          weight: 400
        - asset: assets/fonts/Eina01-Light.ttf
          weight: 300
        - asset: assets/fonts/Eina01-Bold.ttf
          weight: 700
        - asset: assets/fonts/Eina01-SemiBold.ttf
          weight: 600
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

